# -*- mode: ruby -*-
# vi: set ft=ruby :

CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "user-data")
CONFIG = File.join(File.dirname(__FILE__), "config.rb")

$num_instances = 1
$instance_name_prefix = "core"
$update_channel = "alpha"
$image_version = "current"

Vagrant.configure(2) do |config|
	
	config.vm.box = "coreos-%s" % $update_channel
	config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % $update_channel
	config.ssh.insert_key = false
	config.vbguest.auto_update = false
	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 1
		vb.memory = "1024"
	end
	
	
	(1..$num_instances).each do |i|
		config.vm.define vm_name = "%s%02d" % [$instance_name_prefix, i] do |config|
			config.vm.hostname = vm_name
			
			ip = "192.168.56.#{i+100}"
			config.vm.network :private_network, ip: ip
			
			user_data = File.join(File.dirname(__FILE__), "#{vm_name}-user-data.yaml")
			if File.exist?(user_data)
				config.vm.provision :file, :source => "#{user_data}", :destination => "/tmp/vagrantfile-user-data"
				config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
			end
		end
	end
	
end
